version: '3.3'

services:
   mysql:
     image: mysql
     environment:
       MYSQL_DATABASE: muskooters
       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
     volumes:
       - mysql:/var/lib/mysql

   mongo:
     image: mongo
     volumes:
       - mongo:/data/db
     environment:
       MONGO_INITDB_DATABASE: muskooters

   muskooter:
     depends_on:
       - mysql
       - mongo
     build: .
     ports:
     - "3412:3412"
     restart: always
     environment:
       MUSKOOTERS_PORT: :3412
       MUSKOOTERS_MYSQL_URL: root:@tcp(mysql:3306)/muskooters
       MUSKOOTERS_MONGO_URL: mongo:27017/muskooters
       MUSKOOTERS_MONGO_DB_NAME: muskooters
       MUSKOOTERS_MIGRATION_DIR: /go/src/muskooters/migrations

volumes:
  mysql:
  mongo: